version: "3.9"
services:
  speernotes:
    build: .
    container_name: web_api
    ports:
      - "5000:8080"
  sql:
    image: "mssql-2022-full-text"
    container_name: sql_server_22
    ports:
      - "1433:1433" 
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=A55e55ment